name: SurvivalIsland
description: $description
version: '${version}'

main: com.github.Glatinis.survivalIsland.SurvivalIsland
api-version: '26.2'
load: POSTWORLD

authors: [ Glatinis ]

depend: [WorldGuard]
softdepend: [WorldEdit]

commands:
  survivalisland:
    aliases: [si]
    usage: /survivalisland <commandmode|event|rule|spawn|contestant> ...
    permission: survivalisland.admin

permissions:
  survivalisland.admin:
    default: op
  survivalisland.commandmode:
    default: op
